name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.sha }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Update dependencies
      run: pip install --upgrade starlette

    - name: Run tests
      run: pytest

    - name: Docker build
      run: docker build -t myapp:${{ github.sha }} .

    - name: Docker cache
      id: docker-cache
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Docker push
      run: docker push myapp:${{ github.sha }}

    - name: Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: myapp:${{ github.sha }}
        format: table
        exit-code: 1
        ignore-unfixed: true
        severity: CRITICAL,HIGH